### ISSUE TITLE
Cannot use components as content for modals in lazy loaded modules

### ISSUE THREAD

**Issue by TVrijdag** [ng-bootstrap/ng-bootstrap#947]
### Bug description:

The feature to open components as content for modals does not work in lazy loaded modules.
The plunker below throws the error:  No component factory found for NgbdModalContent

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/O8bkySFwvCS1zt9emQSV?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2.1.0

ng-bootstrap: 1.0.0-alpha.9

Bootstrap: 4.0.0-alpha.4

**Comment by pkozlowski-opensource** [comment]
Oh, I see what is going on - it turns out that a lazy loaded module gets its own `ComponentFactoryResolver` and we are always using one from the root module. 

It will require a bit of code reshuffling to fix but should be resolved in alpha.10.

**Comment by pkozlowski-opensource** [comment]
OK, got a fix for this one, preparing a PR.

**Comment by mhmo91** [comment]
Guys, i'm still running into the same problem @pkozlowski-opensource 
"@angular/common": "2.2.1",
    "@angular/router": "3.2.1",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.14"
It's so frustrating... my setup is the same except that i have the two components separated, and one of them is used as content for the modal, and the other with a button to open the modal, both are imported and declared in that lazy loaded modules...

**Comment by jscharett** [comment]
This appears to be broken again?  The plunker example no longer opens a dialog.  Has anyone been able to open a component from a lazy loaded module?  Is this an issue with Angular itself? [14324](https://github.com/angular/angular/issues/14324)

**Comment by jscharett** [comment]
The plunker example on [1220](https://github.com/ng-bootstrap/ng-bootstrap/issues/1220) seems to work, but I am still unable to get this working on my local.  Using Angular 4.4.3 and ng-bootstrap 1.0.0-beta.5

**Comment by jscharett** [comment]
Nvrmind.  After digging in a bit, it appears to be working, just not visible.  Believe it to be an CSS issue with the in house bootstrap theme my company uses.
